project:
  type: website
  output-dir: docs
  preview: 
    port: 55555

website:
  title: "WebTrial2"
  description: "Nothing"
  cookie-consent: true
  page-footer: "CopyrightÂ© 2025 Soyoung KIM."
  announcement: 
    content: "This site is under construction."
  navbar:
    left:
      - text: "{{< fa home >}} Home"
        href: index.qmd
      - text: "{{< fa user >}} About"
        href: about/index.qmd
      - text: "{{< fa person-chalkboard >}} Teaching"
        href: teaching/index.qmd
      - text: "{{< fa flask >}} Research"
        href: research/index.qmd
      - text: "{{< fa lightbulb >}} Examples"
        href: examples/index.qmd
      - playground.qmd
      - dashboard.qmd
    right:
      - icon: github
        href: https://www.github.com
        target: "_blank" # open in a new tap

  sidebar:
    - title: "{{< fa lightbulb >}} Examples"
      contents:
        # - examples/index.qmd
        - auto: examples/*

format:
  html:
    theme:
      - Spacelab
    #  - custom.scss
      - brand
    #css: styles.css
    toc: true

editor: visual

